---
- name: Manage Docker Compose Services
  hosts: localhost
  become: true
  gather_facts: no  # This skips fact gathering
  vars_files:
    - volt.yml  # This should contain the vault secrets

  tasks:
    - name: Render Docker Compose template
      ansible.builtin.template:
        src: docker-compose.yml.j2
        dest: /mnt/c/Users/DELL/Desktop/Cloud/cloud/ansible-projects/docker-compose.yml

    - name: Start Docker Compose services
      community.docker.docker_compose:
        project_src: /mnt/c/Users/DELL/Desktop/Cloud/cloud/ansible-projects
        state: present
